name: AntiDupe
main: AntiDupe\AntiDupe
version: 1.1
api: 3.0.0, 4.0.0
load: STARTUP
description: An advanced plugin to stop item duplication on your server.
website: https://github.com/BlockNetworks/AntiDupe
